### ISSUE TITLE
Add snippets for creating custom validators

### ISSUE THREAD

**Issue by heikkilamarko** [DanWahlin/Angular2-Snippets#1]
Having snippets for creating custom validator functions and classes would be very useful.

**Comment by DanWahlin** [comment]
Really sorry for the extremely late response. I normally get notified via email with issues that are submitted but didn't for this repository for some reason so I never saw it until now.

Happy to add something like that. Let me know if you have a particular format/snippet for that type of code that you'd like to see though. Are you looking for something like these? https://github.com/DanWahlin/Angular-JumpStart/blob/master/src/app/core/services/validation.service.ts

**Comment by DanWahlin** [comment]
Closing this since I need to hear more specifics in order to add it. Feel free to open a new issue if you have a specific code sample you have that you'd like me to base a snippet on.
