### ISSUE TITLE
Remove moduleId from Component snippet

### ISSUE THREAD

**Issue by deckerbd** [DanWahlin/Angular2-Snippets#4]
Since the moduleId declaration is no longer recommended practice, it ought to be removed from the snippet. 

Related pull request: #3

More info here: https://angular.io/guide/change-log#all-mention-of-moduleid-removed-component-relative-paths-guide-deleted-2017-03-13

**Comment by DanWahlin** [comment]
Appreciate it! I've been meaning to do that for the snippets and other projects so thanks for taking the initiative there.
